[IMP] gse_custo: add last payment date on vendor invoice
sbuhl/gse_custo pull request #10
Opened 2023-02-11 20:18 UTC by shortcut1337

Purpose

Dans le cadre des déductions de TVA, qui sont basées sur la date de paiement, nous avons besoin de voir la date du dernier paiement reçu.

Specification

Ajouter dans la vue-list Compta > Fournisseurs > Facture, un champ "dernière date de paiement"

Closes #6

2023-02-11 20:18 UTC, shortcut1337 commented on __manifest__.py
> +        'industry_fsm_report',
Need a cause de https://github.com/sbuhl/gse_custo/commit/945899cca0219d7a135eaf20f63eb88401af9023#diff-c973be6ef39b850d7d0181475d706740d2b5f40c48b87c8eb3ea78c84cbbcde2R6

2023-02-11 20:18 UTC, shortcut1337 commented on views/project_task.xml
> +		<!-- <record id="project_kanban_inherit_project_gse" model="ir.ui.view">
TODO: voir discord https://discord.com/channels/@me/695234725605802044/1074060081441812480

2023-02-15 14:01 UTC, sbuhl requested changes

2023-02-26 19:15 UTC, shortcut1337 commented on views/project_task.xml
> +		<!-- <record id="project_kanban_inherit_project_gse" model="ir.ui.view">
Le code est bien, faut juste que je fixe la DB de prod, y'a un soucis avec la vue Odoo, voir https://discord.com/channels/@me/695234725605802044/1079479624439959654

Rien de grave, c'est juste que ce "388" doit absolument disparaitre :+1: (dans cette vue et dans celle héritée)

2023-02-26 19:17 UTC, shortcut1337 commented on models/account_move.py
> +    derniere_date_paiement = fields.Date()
Ok, je ne savais pas ce que tu voulais exactement, c'est pour ça que je posais la question là bas: https://github.com/sbuhl/gse_custo/issues/6#issuecomment-1426863373

On it :+1:

2023-02-26 19:35 UTC, shortcut1337 commented on __manifest__.py
> +        'mrp',
https://github.com/sbuhl/gse_custo/pull/9/files#r1103685634

2023-02-26 19:52 UTC, shortcut1337 commented on views/recouvrement.xml
> +									       attrs="{'invisible': [('move_type', '!=', 'in_invoice')]}"/>
> je le voulais dans la vue liste des factures

Whoops, je l'avoue aussi là bas, mais je le laisse dans la vue form également, non ?

> (client et fournisseur)

Ah, ce n'était pas que Fournisseur ? `Ajouter dans la vue-list Compta > Fournisseurs > Facture, un champ "dernière date de paiement`

Mais je l'ajoute aussi aux factures clients :+1:

2023-02-26 21:26 UTC, shortcut1337 commented on views/recouvrement.xml
> +									       attrs="{'invisible': [('move_type', '!=', 'in_invoice')]}"/>
Ajouté

2023-02-26 21:27 UTC, shortcut1337 commented on models/account_move.py
> +    derniere_date_paiement = fields.Date()
C'est assez difficile à tester localement: il faut reconcilier un paiement avc un bank statement pour que l'invoice soit marquée comme payée :thinking: ?
En local, no idea de comment faire.
J'ai testé le dévelopement sur runbot avec studio (pour y foutre l'équivelent de mon computed field) et ça semble fonctionner as expected :+1:

2023-03-08 10:55 UTC, sbuhl approved these changes
J'ai testé et ça me semble ok.
On peut merger?

2023-04-12 13:20 UTC, closed without merging